-- require("")

require("monitors")
-- require("programs")
require("autostart")
-- require("env-var")
-- require("permissions")
require("look")
-- require("misc")
require("inputs")
require("keybinds")
require("scrollingLayout")
-- require("dwindle-layout")
-- require("master-layout")

require("window-rules")
require("graphics")
require("noctalia")
